insert into product (product_id, product_name, category, price, cost_price) values (1, 'Cheese - Ermite Bleu', 'Electrical', 113, 40);
insert into product (product_id, product_name, category, price, cost_price) values (2, 'Wine - Champagne Brut Veuve', 'Temp Fencing, Decorative Fencing and Gates', 123, 32);
insert into product (product_id, product_name, category, price, cost_price) values (3, 'Wine - Prosecco Valdobienne', 'Overhead Doors', 190, 74);
insert into product (product_id, product_name, category, price, cost_price) values (4, 'Juice Peach Nectar', 'Exterior Signage', 186, 20);
insert into product (product_id, product_name, category, price, cost_price) values (5, 'Bar Bran Honey Nut', 'Fire Sprinkler System', 198, 62);
insert into product (product_id, product_name, category, price, cost_price) values (6, 'Gherkin - Sour', 'Retaining Wall and Brick Pavers', 126, 76);
insert into product (product_id, product_name, category, price, cost_price) values (7, 'Jam - Raspberry,jar', 'Temp Fencing, Decorative Fencing and Gates', 129, 84);
insert into product (product_id, product_name, category, price, cost_price) values (8, 'Lettuce - Arugula', 'Casework', 186, 36);
insert into product (product_id, product_name, category, price, cost_price) values (9, 'Cherries - Bing, Canned', 'Masonry', 138, 71);
insert into product (product_id, product_name, category, price, cost_price) values (10, 'Soup - Base Broth Chix', 'Electrical and Fire Alarm', 156, 30);
insert into product (product_id, product_name, category, price, cost_price) values (11, 'Onions - Spanish', 'Drywall & Acoustical (MOB)', 130, 66);
insert into product (product_id, product_name, category, price, cost_price) values (12, 'Tia Maria', 'Roofing (Metal)', 195, 42);
insert into product (product_id, product_name, category, price, cost_price) values (13, 'Juice - Tomato, 48 Oz', 'Doors, Frames & Hardware', 111, 49);
insert into product (product_id, product_name, category, price, cost_price) values (14, 'Potatoes - Yukon Gold 5 Oz', 'Fire Protection', 116, 47);
insert into product (product_id, product_name, category, price, cost_price) values (15, 'Jack Daniels', 'Prefabricated Aluminum Metal Canopies', 121, 33);
insert into product (product_id, product_name, category, price, cost_price) values (16, 'Wakami Seaweed', 'Overhead Doors', 105, 76);
insert into product (product_id, product_name, category, price, cost_price) values (17, 'Soup - French Can Pea', 'Retaining Wall and Brick Pavers', 191, 73);
insert into product (product_id, product_name, category, price, cost_price) values (18, 'Wine - Toasted Head', 'Overhead Doors', 128, 84);
insert into product (product_id, product_name, category, price, cost_price) values (19, 'Chocolate - Liqueur Cups With Foil', 'Hard Tile & Stone', 175, 71);
insert into product (product_id, product_name, category, price, cost_price) values (20, 'Rappini - Andy Boy', 'Masonry & Precast', 167, 64);
insert into product (product_id, product_name, category, price, cost_price) values (21, 'Coffee - French Vanilla Frothy', 'Masonry & Precast', 115, 30);
insert into product (product_id, product_name, category, price, cost_price) values (22, 'Wakami Seaweed', 'Electrical and Fire Alarm', 116, 23);
insert into product (product_id, product_name, category, price, cost_price) values (23, 'Mushroom - Morels, Dry', 'Temp Fencing, Decorative Fencing and Gates', 187, 17);
insert into product (product_id, product_name, category, price, cost_price) values (24, 'Oyster - In Shell', 'Overhead Doors', 154, 61);
insert into product (product_id, product_name, category, price, cost_price) values (25, 'Bread - White, Unsliced', 'Drilled Shafts', 141, 72);
insert into product (product_id, product_name, category, price, cost_price) values (26, 'Beef - Tenderloin - Aa', 'Doors, Frames & Hardware', 178, 14);
insert into product (product_id, product_name, category, price, cost_price) values (27, 'Mountain Dew', 'Termite Control', 139, 90);
insert into product (product_id, product_name, category, price, cost_price) values (28, 'Milk - Chocolate 500ml', 'Elevator', 129, 62);
insert into product (product_id, product_name, category, price, cost_price) values (29, 'Pepper - Chipotle, Canned', 'Prefabricated Aluminum Metal Canopies', 193, 89);
insert into product (product_id, product_name, category, price, cost_price) values (30, 'Flour - Chickpea', 'Prefabricated Aluminum Metal Canopies', 168, 71);
insert into product (product_id, product_name, category, price, cost_price) values (31, 'Mushroom - Chantrelle, Fresh', 'Marlite Panels (FED)', 176, 30);
insert into product (product_id, product_name, category, price, cost_price) values (32, 'Table Cloth - 53x69 Colour', 'Curb & Gutter', 123, 44);
insert into product (product_id, product_name, category, price, cost_price) values (33, 'Appetizer - Seafood Assortment', 'Doors, Frames & Hardware', 187, 94);
insert into product (product_id, product_name, category, price, cost_price) values (34, 'Magnotta Bel Paese Red', 'Retaining Wall and Brick Pavers', 164, 58);
insert into product (product_id, product_name, category, price, cost_price) values (35, 'Coffee - Frthy Coffee Crisp', 'Retaining Wall and Brick Pavers', 127, 59);
insert into product (product_id, product_name, category, price, cost_price) values (36, 'Jolt Cola - Red Eye', 'Casework', 106, 99);
insert into product (product_id, product_name, category, price, cost_price) values (37, 'Poppy Seed', 'Prefabricated Aluminum Metal Canopies', 133, 25);
insert into product (product_id, product_name, category, price, cost_price) values (38, 'Pumpkin', 'Drywall & Acoustical (MOB)', 156, 83);
insert into product (product_id, product_name, category, price, cost_price) values (39, 'Flour - Buckwheat, Dark', 'Temp Fencing, Decorative Fencing and Gates', 118, 94);
insert into product (product_id, product_name, category, price, cost_price) values (40, 'Numi - Assorted Teas', 'Fire Protection', 186, 32);
insert into product (product_id, product_name, category, price, cost_price) values (41, 'Potatoes - Parissienne', 'Curb & Gutter', 152, 93);
insert into product (product_id, product_name, category, price, cost_price) values (42, 'Chocolate - Feathers', 'Rebar & Wire Mesh Install', 116, 54);
insert into product (product_id, product_name, category, price, cost_price) values (43, 'Tomatoes Tear Drop', 'Exterior Signage', 164, 62);
insert into product (product_id, product_name, category, price, cost_price) values (44, 'Muffin - Carrot Individual Wrap', 'Plumbing & Medical Gas', 155, 58);
insert into product (product_id, product_name, category, price, cost_price) values (45, 'Bread - Bistro White', 'Plumbing & Medical Gas', 200, 74);
insert into product (product_id, product_name, category, price, cost_price) values (46, 'Shrimp - Black Tiger 8 - 12', 'Epoxy Flooring', 185, 31);
insert into product (product_id, product_name, category, price, cost_price) values (47, 'Wine - White, Pinot Grigio', 'EIFS', 198, 53);
insert into product (product_id, product_name, category, price, cost_price) values (48, 'Wine - Vovray Sec Domaine Huet', 'Granite Surfaces', 128, 25);
insert into product (product_id, product_name, category, price, cost_price) values (49, 'Flower - Dish Garden', 'Fire Protection', 140, 82);
insert into product (product_id, product_name, category, price, cost_price) values (50, 'Wine - Muscadet Sur Lie', 'HVAC', 164, 32);
insert into product (product_id, product_name, category, price, cost_price) values (51, 'Water, Tap', 'Wall Protection', 196, 93);
insert into product (product_id, product_name, category, price, cost_price) values (52, 'Jam - Apricot', 'Painting & Vinyl Wall Covering', 162, 39);
insert into product (product_id, product_name, category, price, cost_price) values (53, 'Carroway Seed', 'Framing (Wood)', 104, 72);
insert into product (product_id, product_name, category, price, cost_price) values (54, 'Petite Baguette', 'Electrical', 111, 65);
insert into product (product_id, product_name, category, price, cost_price) values (55, 'Cabbage - Nappa', 'Structural & Misc Steel Erection', 182, 90);
insert into product (product_id, product_name, category, price, cost_price) values (56, 'Chips Potato All Dressed - 43g', 'Drywall & Acoustical (MOB)', 189, 95);
insert into product (product_id, product_name, category, price, cost_price) values (57, 'Soup - Campbells - Chicken Noodle', 'Electrical', 151, 18);
insert into product (product_id, product_name, category, price, cost_price) values (58, 'Veal - Ground', 'Temp Fencing, Decorative Fencing and Gates', 172, 95);
insert into product (product_id, product_name, category, price, cost_price) values (59, 'Roe - Lump Fish, Black', 'Overhead Doors', 174, 19);
insert into product (product_id, product_name, category, price, cost_price) values (60, 'Nantucket - 518ml', 'Plumbing & Medical Gas', 177, 42);
insert into product (product_id, product_name, category, price, cost_price) values (61, 'Crab - Imitation Flakes', 'Electrical', 193, 88);
insert into product (product_id, product_name, category, price, cost_price) values (62, 'Cookies Cereal Nut', 'Temp Fencing, Decorative Fencing and Gates', 145, 86);
insert into product (product_id, product_name, category, price, cost_price) values (63, 'Soup Campbells', 'Rebar & Wire Mesh Install', 109, 81);
insert into product (product_id, product_name, category, price, cost_price) values (64, 'Broom And Broom Rack White', 'Asphalt Paving', 121, 61);
insert into product (product_id, product_name, category, price, cost_price) values (65, 'Pickerel - Fillets', 'Fire Sprinkler System', 169, 23);
insert into product (product_id, product_name, category, price, cost_price) values (66, 'Milk - Chocolate 250 Ml', 'Roofing (Asphalt)', 173, 61);
insert into product (product_id, product_name, category, price, cost_price) values (67, 'Wine - Riesling Dr. Pauly', 'Termite Control', 150, 31);
insert into product (product_id, product_name, category, price, cost_price) values (68, 'Bagels Poppyseed', 'Roofing (Metal)', 149, 24);
insert into product (product_id, product_name, category, price, cost_price) values (69, 'Chips - Potato Jalapeno', 'Exterior Signage', 154, 34);
insert into product (product_id, product_name, category, price, cost_price) values (70, 'Wine - Riesling Dr. Pauly', 'Structural and Misc Steel (Fabrication)', 142, 41);
insert into product (product_id, product_name, category, price, cost_price) values (71, 'Sobe - Tropical Energy', 'EIFS', 136, 100);
insert into product (product_id, product_name, category, price, cost_price) values (72, 'Bread - Assorted Rolls', 'Elevator', 166, 78);
insert into product (product_id, product_name, category, price, cost_price) values (73, 'Wine - Tio Pepe Sherry Fino', 'Drywall & Acoustical (FED)', 168, 19);
insert into product (product_id, product_name, category, price, cost_price) values (74, 'Banana - Leaves', 'Masonry & Precast', 185, 49);
insert into product (product_id, product_name, category, price, cost_price) values (75, 'Thermometer Digital', 'Sitework & Site Utilities', 186, 47);
insert into product (product_id, product_name, category, price, cost_price) values (76, 'Wine - Merlot Vina Carmen', 'Waterproofing & Caulking', 130, 77);
insert into product (product_id, product_name, category, price, cost_price) values (77, 'Rosemary - Dry', 'Glass & Glazing', 156, 33);
insert into product (product_id, product_name, category, price, cost_price) values (78, 'Bag Stand', 'Construction Clean and Final Clean', 145, 15);
insert into product (product_id, product_name, category, price, cost_price) values (79, 'Table Cloth 54x72 White', 'Plumbing & Medical Gas', 193, 93);
insert into product (product_id, product_name, category, price, cost_price) values (80, 'Potatoes - Yukon Gold 5 Oz', 'Masonry & Precast', 177, 52);
insert into product (product_id, product_name, category, price, cost_price) values (81, 'Tea - Green', 'Marlite Panels (FED)', 126, 12);
insert into product (product_id, product_name, category, price, cost_price) values (82, 'Table Cloth 54x54 Colour', 'Ornamental Railings', 136, 70);
insert into product (product_id, product_name, category, price, cost_price) values (83, 'Pastry - Butterscotch Baked', 'Framing (Wood)', 113, 11);
insert into product (product_id, product_name, category, price, cost_price) values (84, 'Kahlua', 'EIFS', 154, 25);
insert into product (product_id, product_name, category, price, cost_price) values (85, 'Sauce - White, Mix', 'Glass & Glazing', 120, 40);
insert into product (product_id, product_name, category, price, cost_price) values (86, 'Napkin White - Starched', 'Site Furnishings', 197, 60);
insert into product (product_id, product_name, category, price, cost_price) values (87, 'Salt - Rock, Course', 'Curb & Gutter', 198, 25);
insert into product (product_id, product_name, category, price, cost_price) values (88, 'Trout - Smoked', 'Structural and Misc Steel (Fabrication)', 165, 91);
insert into product (product_id, product_name, category, price, cost_price) values (89, 'Orange - Blood', 'Masonry', 133, 39);
insert into product (product_id, product_name, category, price, cost_price) values (90, 'Island Oasis - Cappucino Mix', 'Electrical and Fire Alarm', 195, 74);
insert into product (product_id, product_name, category, price, cost_price) values (91, 'Wine - Red, Cooking', 'Epoxy Flooring', 193, 37);
insert into product (product_id, product_name, category, price, cost_price) values (92, 'Cheese - Cambozola', 'Prefabricated Aluminum Metal Canopies', 177, 62);
insert into product (product_id, product_name, category, price, cost_price) values (93, 'Trout - Rainbow, Frozen', 'Wall Protection', 106, 44);
insert into product (product_id, product_name, category, price, cost_price) values (94, 'Apple - Custard', 'Curb & Gutter', 129, 86);
insert into product (product_id, product_name, category, price, cost_price) values (95, 'Pepper - Jalapeno', 'Roofing (Metal)', 116, 28);
insert into product (product_id, product_name, category, price, cost_price) values (96, 'Chocolate - Milk, Callets', 'Drywall & Acoustical (MOB)', 116, 50);
insert into product (product_id, product_name, category, price, cost_price) values (97, 'Cheese - Havarti, Roasted Garlic', 'Painting & Vinyl Wall Covering', 173, 81);
insert into product (product_id, product_name, category, price, cost_price) values (98, 'Ham - Smoked, Bone - In', 'Wall Protection', 189, 17);
insert into product (product_id, product_name, category, price, cost_price) values (99, 'Potatoes - Parissienne', 'Prefabricated Aluminum Metal Canopies', 155, 22);
insert into product (product_id, product_name, category, price, cost_price) values (100, 'Lady Fingers', 'Structural and Misc Steel (Fabrication)', 163, 91);
